In [13]:
%load_ext sql

# Connect SQLMagic directly to the project DuckDB file.
%sql duckdb:///f:/Project/games/jt3/data/jt3.duckdb

%config SqlMagic.autopolars = True

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [14]:
%%sql
SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_type = 'BASE TABLE'
ORDER BY table_schema, table_name

Running query in 'duckdb:///f:/Project/games/jt3/data/jt3.duckdb'

shape: (6, 2)
┌──────────────┬─────────────────┐
│ table_schema ┆ table_name      │
│ ---          ┆ ---             │
│ str          ┆ str             │
╞══════════════╪═════════════════╡
│ main         ┆ categories      │
│ main         ┆ clue_embeddings │
│ main         ┆ clues           │
│ main         ┆ contestants     │
│ main         ┆ episodes        │
│ main         ┆ rounds          │
└──────────────┴─────────────────┘

In [15]:
%%sql
SELECT * FROM categories

Running query in 'duckdb:///f:/Project/games/jt3/data/jt3.duckdb'

shape: (64_920, 5)
┌─────────┬─────────────┬────────────────┬────────────────────────────┬──────────┐
│ game_id ┆ round_index ┆ category_index ┆ name                       ┆ comments │
│ ---     ┆ ---         ┆ ---            ┆ ---                        ┆ ---      │
│ i32     ┆ i32         ┆ i32            ┆ str                        ┆ str      │
╞═════════╪═════════════╪════════════════╪════════════════════════════╪══════════╡
│ 9263    ┆ 0           ┆ 0              ┆ EDIBLE IDIOMS              ┆ null     │
│ 9263    ┆ 0           ┆ 1              ┆ BUSINESS HISTORY           ┆ null     │
│ 9263    ┆ 0           ┆ 2              ┆ BIOLOGY                    ┆ null     │
│ 9263    ┆ 0           ┆ 3              ┆ BICYCLES ON THE BIG SCREEN ┆ null     │
│ 9263    ┆ 0           ┆ 4              ┆ PLAIN                      ┆ null     │
│ …       ┆ …           ┆ …              ┆ …                          ┆ …        │
│ 1424    ┆ 1           ┆ 2              ┆ SIEGES                     ┆ null     │
│ 1424    ┆ 1           ┆ 3              ┆ COLLEGES & UNIVERSITIES    ┆ null     │
│ 1424    ┆ 1           ┆ 4              ┆ BEASTLY LIT                ┆ null     │
│ 1424    ┆ 1           ┆ 5              ┆ OTHER ALPHABETS' LETTERS   ┆ null     │
│ 1424    ┆ 2           ┆ 0              ┆ THE 1950s                  ┆ null     │
└─────────┴─────────────┴────────────────┴────────────────────────────┴──────────┘

In [16]:
%%sql
SELECT * FROM clues

Running query in 'duckdb:///f:/Project/games/jt3/data/jt3.duckdb'

shape: (296_438, 10)
┌─────────┬────────────┬────────────┬─────────┬───┬────────────┬────────────┬───────────┬──────────┐
│ game_id ┆ round_inde ┆ category_i ┆ clue_id ┆ … ┆ is_daily_d ┆ text       ┆ correct_r ┆ answerer │
│ ---     ┆ x          ┆ ndex       ┆ ---     ┆   ┆ ouble      ┆ ---        ┆ esponse   ┆ ---      │
│ i32     ┆ ---        ┆ ---        ┆ str     ┆   ┆ ---        ┆ str        ┆ ---       ┆ str      │
│         ┆ i32        ┆ i32        ┆         ┆   ┆ bool       ┆            ┆ str       ┆          │
╞═════════╪════════════╪════════════╪═════════╪═══╪════════════╪════════════╪═══════════╪══════════╡
│ 9263    ┆ 0          ┆ 0          ┆ J_1_1   ┆ … ┆ false      ┆ It's       ┆ a hill of ┆ null     │
│         ┆            ┆            ┆         ┆   ┆            ┆ something  ┆ beans     ┆          │
│         ┆            ┆            ┆         ┆   ┆            ┆ of little  ┆           ┆          │
│         ┆            ┆            ┆         ┆   ┆            ┆ impor…     ┆           ┆          │
│ 9263    ┆ 0          ┆ 0          ┆ J_1_2   ┆ … ┆ false      ┆ In a 1785  ┆ variety   ┆ null     │
│         ┆            ┆            ┆         ┆   ┆            ┆ poem       ┆           ┆          │
│         ┆            ┆            ┆         ┆   ┆            ┆ William    ┆           ┆          │
│         ┆            ┆            ┆         ┆   ┆            ┆ Cowper …   ┆           ┆          │
│ 9263    ┆ 0          ┆ 0          ┆ J_1_3   ┆ … ┆ false      ┆ At the     ┆ a hot     ┆ null     │
│         ┆            ┆            ┆         ┆   ┆            ┆ dinner     ┆ potato    ┆          │
│         ┆            ┆            ┆         ┆   ┆            ┆ table, it  ┆           ┆          │
│         ┆            ┆            ┆         ┆   ┆            ┆ can be…    ┆           ┆          │
│ 9263    ┆ 0          ┆ 0          ┆ J_1_4   ┆ … ┆ false      ┆ TV's "Myth ┆ take      ┆ null     │
│         ┆            ┆            ┆         ┆   ┆            ┆ Busters"   ┆ candy     ┆          │
│         ┆            ┆            ┆         ┆   ┆            ┆ once       ┆ from a    ┆          │
│         ┆            ┆            ┆         ┆   ┆            ┆ tested…    ┆ baby      ┆          │
│ 9263    ┆ 0          ┆ 0          ┆ J_1_5   ┆ … ┆ false      ┆ This       ┆ kettle of ┆ null     │
│         ┆            ┆            ┆         ┆   ┆            ┆ 3-word     ┆ fish      ┆          │
│         ┆            ┆            ┆         ┆   ┆            ┆ term once  ┆           ┆          │
│         ┆            ┆            ┆         ┆   ┆            ┆ referred…  ┆           ┆          │
│ …       ┆ …          ┆ …          ┆ …       ┆ … ┆ …          ┆ …          ┆ …         ┆ …        │
│ 1424    ┆ 1          ┆ 5          ┆ DJ_6_2  ┆ … ┆ false      ┆ (Sarah of  ┆ alef &    ┆ null     │
│         ┆            ┆            ┆         ┆   ┆            ┆ the Clue   ┆ bet       ┆          │
│         ┆            ┆            ┆         ┆   ┆            ┆ Crew       ┆           ┆          │
│         ┆            ┆            ┆         ┆   ┆            ┆ report…    ┆           ┆          │
│ 1424    ┆ 1          ┆ 5          ┆ DJ_6_3  ┆ … ┆ false      ┆ The combin ┆ Korean    ┆ null     │
│         ┆            ┆            ┆         ┆   ┆            ┆ ation of   ┆           ┆          │
│         ┆            ┆            ┆         ┆   ┆            ┆ consonants ┆           ┆          │
│         ┆            ┆            ┆         ┆   ┆            ┆ …          ┆           ┆          │
│ 1424    ┆ 1          ┆ 5          ┆ DJ_6_4  ┆ … ┆ false      ┆ These 2    ┆ chi and   ┆ null     │
│         ┆            ┆            ┆         ┆   ┆            ┆ Greek      ┆ rho       ┆          │
│         ┆            ┆            ┆         ┆   ┆            ┆ letters    ┆           ┆          │
│         ┆            ┆            ┆         ┆   ┆            ┆ begin th…  ┆           ┆          │
│ 1424    ┆ 1          ┆ 5          ┆ DJ_6_5  ┆ … ┆ true       ┆ Seenherear ┆ the Thai  ┆ null     │
│         ┆            ┆            ┆         ┆   ┆            ┆ e the      ┆ or        ┆          │
│         ┆            ┆            ┆         ┆   ┆            ┆ first &    ┆ Siamese   ┆          │
│         ┆            ┆            ┆         ┆   ┆            ┆ last l…    ┆ alphabet  ┆          │
│ 1424    ┆ 2          ┆ 0          ┆ FJ      ┆ … ┆ false      ┆ On a March ┆ Edward R. ┆ null     │
│         ┆            ┆            ┆         ┆   ┆            ┆ 9, 1954    ┆ Murrow    ┆          │
│         ┆            ┆            ┆         ┆   ┆            ┆ broadcast, ┆           ┆          │
│         ┆            ┆            ┆         ┆   ┆            ┆ …          ┆           ┆          │
└─────────┴────────────┴────────────┴─────────┴───┴────────────┴────────────┴───────────┴──────────┘

In [17]:
%%sql
SELECT * FROM contestants

Running query in 'duckdb:///f:/Project/games/jt3/data/jt3.duckdb'

shape: (15_069, 4)
┌─────────┬──────────────────────┬─────────────────────────────────┬───────────┐
│ game_id ┆ name                 ┆ description                     ┆ player_id │
│ ---     ┆ ---                  ┆ ---                             ┆ ---       │
│ i32     ┆ str                  ┆ str                             ┆ i32       │
╞═════════╪══════════════════════╪═════════════════════════════════╪═══════════╡
│ 9263    ┆ Josh Jackson         ┆ an urban planner from Pasadena… ┆ 18141     │
│ 9263    ┆ Caroline Paul        ┆ an HR specialist from Washingt… ┆ 18142     │
│ 9263    ┆ Jonathan Hugendubler ┆ an adjunct professor and trivi… ┆ 18139     │
│ 9264    ┆ Ian Morrison         ┆ an airline ramp agent original… ┆ 18143     │
│ 9264    ┆ Stacy Shelly         ┆ an attorney from Rockford, Ill… ┆ 18144     │
│ …       ┆ …                    ┆ …                               ┆ …         │
│ 1425    ┆ Linda Flink          ┆ a healthcare consultant from S… ┆ 2904      │
│ 1425    ┆ Bob Hutton           ┆ a grad student originally from… ┆ 2905      │
│ 1424    ┆ Bob Hutton           ┆ a grad student originally from… ┆ 2905      │
│ 1424    ┆ Sue Bryant           ┆ a stay-at-home mom from Ellico… ┆ 2906      │
│ 1424    ┆ Sean Dillon          ┆ a college instructor from Pasa… ┆ 2874      │
└─────────┴──────────────────────┴─────────────────────────────────┴───────────┘

In [18]:
%%sql
SELECT * FROM episodes

Running query in 'duckdb:///f:/Project/games/jt3/data/jt3.duckdb'

shape: (5_000, 3)
┌─────────┬─────────────┬────────────┐
│ game_id ┆ show_number ┆ air_date   │
│ ---     ┆ ---         ┆ ---        │
│ i32     ┆ i32         ┆ date       │
╞═════════╪═════════════╪════════════╡
│ 9263    ┆ 9386        ┆ 2025-09-08 │
│ 9264    ┆ 9387        ┆ 2025-09-09 │
│ 9265    ┆ 9388        ┆ 2025-09-10 │
│ 9266    ┆ 9389        ┆ 2025-09-11 │
│ 9267    ┆ 9390        ┆ 2025-09-12 │
│ …       ┆ …           ┆ …          │
│ 1433    ┆ 5120        ┆ 2006-12-08 │
│ 1432    ┆ 5119        ┆ 2006-12-07 │
│ 1431    ┆ 5118        ┆ 2006-12-06 │
│ 1425    ┆ 5117        ┆ 2006-12-05 │
│ 1424    ┆ 5116        ┆ 2006-12-04 │
└─────────┴─────────────┴────────────┘

In [19]:
%%sql
SELECT * FROM rounds

Running query in 'duckdb:///f:/Project/games/jt3/data/jt3.duckdb'

shape: (14_980, 3)
┌─────────┬─────────────┬──────────────────┐
│ game_id ┆ round_index ┆ name             │
│ ---     ┆ ---         ┆ ---              │
│ i32     ┆ i32         ┆ str              │
╞═════════╪═════════════╪══════════════════╡
│ 9263    ┆ 0           ┆ Jeopardy!        │
│ 9263    ┆ 1           ┆ Double Jeopardy! │
│ 9263    ┆ 2           ┆ Final Jeopardy!  │
│ 9264    ┆ 0           ┆ Jeopardy!        │
│ 9264    ┆ 1           ┆ Double Jeopardy! │
│ …       ┆ …           ┆ …                │
│ 1425    ┆ 1           ┆ Double Jeopardy! │
│ 1425    ┆ 2           ┆ Final Jeopardy!  │
│ 1424    ┆ 0           ┆ Jeopardy!        │
│ 1424    ┆ 1           ┆ Double Jeopardy! │
│ 1424    ┆ 2           ┆ Final Jeopardy!  │
└─────────┴─────────────┴──────────────────┘

In [20]:
%%sql clues <<
SELECT
    c.game_id,
    cat.name AS category,
    c.text AS clue_text,
    c.correct_response
FROM clues AS c
JOIN categories AS cat
    ON c.game_id = cat.game_id
   AND c.round_index = cat.round_index
   AND c.category_index = cat.category_index
ORDER BY c.game_id DESC, c.round_index, c.category_index, c.clue_order

Running query in 'duckdb:///f:/Project/games/jt3/data/jt3.duckdb'

In [21]:
clues

shape: (296_438, 4)
┌─────────┬───────────────┬─────────────────────────────────┬──────────────────────┐
│ game_id ┆ category      ┆ clue_text                       ┆ correct_response     │
│ ---     ┆ ---           ┆ ---                             ┆ ---                  │
│ i32     ┆ str           ┆ str                             ┆ str                  │
╞═════════╪═══════════════╪═════════════════════════════════╪══════════════════════╡
│ 9424    ┆ START ME "UP" ┆ A difficult struggle is this t… ┆ uphill               │
│ 9424    ┆ START ME "UP" ┆ The title ofthisclassic Britis… ┆ Upstairs, Downstairs │
│ 9424    ┆ START ME "UP" ┆ It's one of the 4 basic boxing… ┆ uppercut             │
│ 9424    ┆ START ME "UP" ┆ In a challenging situation, yo… ┆ up a creek           │
│ 9424    ┆ START ME "UP" ┆ If you're a fast learner, you'… ┆ uptake               │
│ …       ┆ …             ┆ …                               ┆ …                    │
│ 116     ┆ "BOOK"S       ┆ Common pharase that might foll… ┆ I'm in the book!     │
│ 116     ┆ "BOOK"S       ┆ Something set next to a volume… ┆ by the book          │
│ 116     ┆ "BOOK"S       ┆ Samuel Pepys sometimes put one… ┆ a bookplate          │
│ 116     ┆ "BOOK"S       ┆ Famous fooderie, found on 15th… ┆ Bookbinder's         │
│ 116     ┆ THE MILITARY  ┆ Foreign country in which the m… ┆ Germany              │
└─────────┴───────────────┴─────────────────────────────────┴──────────────────────┘